### ISSUE TITLE
Interested in helping out

### ISSUE THREAD

**Issue by hermanbanken** [gimlet-io/gimlet-dashboard#1]
Hi @laszlocph, a GitOps dashboard would be so cool!
I was recently looking at https://codefresh.io/features/gitops/ and something like that would be awesome.

**Comment by laszlocph** [comment]
> Hi @laszlocph, a GitOps dashboard would be so cool!
> I was recently looking at https://codefresh.io/features/gitops/ and something like that would be awesome.

Herman, you are looking at my internal docs? :D

Codefresh is one of my inspirations. Let me tie some loose ends and publish the dashboard kickoff document.

**Comment by laszlocph** [comment]
@hermanbanken https://gimlet.io/blog/gimlet-dashboard-strategy/

Let me know if you find these goals interesting.

**Comment by laszlocph** [comment]
The stack will be: React, Typescript, TailwindCSS
